[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.118.2"
NODE_VERSION = "18.18.0"

[context.production.environment]
HUGO_ENV = "production"
NODE_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"
